#
# Module manifest for module 'LocalUsers'
#
# Generated by: Human.Against.Machine
#
# Generated on: 26/12/2024
#

@{

# Script module or binary module file associated with this manifest.
RootModule = '.\LocalUsers.psm1'

# Version number of this module.
ModuleVersion = '1.2.1'

# Supported PSEditions
CompatiblePSEditions = @('Core')

# ID used to uniquely identify this module
GUID = '90647df0-c6bf-4388-909e-5dcddbb5c7b2'

# Author of this module
Author = 'Human.Against.Machine'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) Human.Against.Machine All rights reserved.'

# Description of the functionality provided by this module
Description = @'
LocalUser helps maintain Windows stability and efficiency, providing enhanced user-centric cmdlets for local user management:

- Get-User
    1. Focuses only on real accounts (excludes built-in system accounts).
    2. Retrieves lost accounts (profiles lacking a name).
    3. Provides session activity details.

-  Remove-User
    1. Completely removes users, including profiles and registry entries.
    2. Optionally backs up user profiles before removal.

-  New-User
    1. Enables fast user creation with a blank password.
'@

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @('Get-User', 'Remove-User', 'New-User', 'Show-User')

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('Windows', 'Users-management', 'Local-users', 'Account-management', 'Local-account')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/HumanAgainstMachine/LocalUsers/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/HumanAgainstMachine/LocalUsers'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
[1.2.1] - 2025-03-17
Change minimum version of the PowerShell engine required by this module to 5.1

[1.2.0] - 2025-01-14
1. Add Show-User, a module GUI, experimental feature.
2. Get-User: Cast `AccountSource` object to string for improved presentation.
3. New-User:
   - Add a username length validation before creating a local account.
   - Refine try-catch handling for "user already exists" exceptions from `New-LocalUser`.
4. Enhance console exception message for unsupported languages.

[1.1.1] - 2025-01-12
- Fix log out when attempting to remove yourself.
- Improve representation of null values for `IdleSessionTime`.

[1.1.0] - 2025-01-11
Read-Quser function:
- Add language compatibility test for English, Italian, German, French, and Spanish. Throw a "Language not supported" exception for unsupported languages.
- Improve `quser` output parsing by using fixed field indices.

[1.0.1] - 2024-12-29
Fixed
- Typos in manifest Description and ReleaseNotes

[1.0.0] - 2024-12-29
Initial Release
- Three cmdlets to manage local users: Get-User, New-User, Remove-User
'@

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

